// GENERATED by istmo-build - DO NOT EDIT MANUALLY.
//
// Regenerate by running the codegen test suite and copying the golden
// output verbatim:
//
//   ISTMO_BUILD_UPDATE_GOLDEN=1 cargo test -p istmo-build --test codegen
//   cp crates/build/tests/golden/permissions_host.swift.expected \
//      examples/rust-mobile-demo/ios/RustMobileDemo/Plugins/Permissions/PermissionsDispatcher.swift
//
// (A `build.rs`-driven emission is on the follow-up list — until then the
// copy above is the checked-in contract with the wire schema.)
//
// plugin id: istmo.permissions

import Foundation
import IstmoRuntime

/// Platform-facing surface for the `Permissions` plugin. Hand-write an
/// impl with the SDK-specific logic; the dispatcher below handles
/// wire encode/decode.
public protocol PermissionsBackend: AnyObject {
    func check(permission: String) async throws -> PermissionStatus
    func request(permissions: [String]) async throws -> [PermissionOutcome]
    func should_show_rationale(permission: String) async throws -> Bool
}

/// Reader / writer per `Named` type referenced by the `Permissions` contract.
/// User provides one impl; each entry typically delegates to a
/// helper on the type itself.
public protocol PermissionsCodecs {
    func readPermissionOutcome(_ c: inout Bincode.Cursor) throws -> PermissionOutcome
    func writePermissionOutcome(_ out: inout Data, _ value: PermissionOutcome)
    func readPermissionStatus(_ c: inout Bincode.Cursor) throws -> PermissionStatus
    func writePermissionStatus(_ out: inout Data, _ value: PermissionStatus)
}

/// Decodes wire calls, invokes `PermissionsBackend`, encodes the response.
/// Register with `IstmoRuntime.shared.registerHandler(PLUGIN_ID, dispatcher)`.
public final class PermissionsDispatcher: PluginHandler {
    public static let PLUGIN_ID: String = "istmo.permissions"

    private let backend: PermissionsBackend
    private let codecs: PermissionsCodecs

    public init(backend: PermissionsBackend, codecs: PermissionsCodecs) {
        self.backend = backend
        self.codecs = codecs
    }

    public func handleCall(instanceId: UInt64, method: String, payload: Data) async throws -> Data {
        switch method {
        case "check":
            var c = Bincode.Cursor(payload)
            let permission = try Bincode.readString(&c)
            let result = try await backend.check(permission: permission)
            var out = Data()
            codecs.writePermissionStatus(&out, result)
            return out
        case "request":
            var c = Bincode.Cursor(payload)
            let permissions = try Bincode.readVec(&c) { try Bincode.readString(&$0) }
            let result = try await backend.request(permissions: permissions)
            var out = Data()
            Bincode.writeVec(&out, result) { codecs.writePermissionOutcome(&$0, $1) }
            return out
        case "should_show_rationale":
            var c = Bincode.Cursor(payload)
            let permission = try Bincode.readString(&c)
            let result = try await backend.should_show_rationale(permission: permission)
            var out = Data()
            Bincode.writeBool(&out, result)
            return out
        default:
            throw PluginRuntimeError.unknownMethod(plugin: "Permissions", method: method)
        }
    }
}
