package dev.istmo.runtime

// GENERATED by istmo-build - DO NOT EDIT.
// plugin id: istmo.admob
import java.io.ByteArrayOutputStream

class AdMobCodecsImpl : AdMobCodecs {

    override fun readAdMobConfig(bytes: ByteArray, offset: Int): Bincode.Decoded<AdMobConfig> {
        var cursor = offset
        val d_appId = Bincode.readString(bytes, cursor)
        cursor = d_appId.consumed
        val appId = d_appId.value
        val d_testDeviceIds = Bincode.readVec(bytes, cursor) { p, o -> Bincode.readString(p, o) }
        cursor = d_testDeviceIds.consumed
        val testDeviceIds = d_testDeviceIds.value
        val d_childDirectedTreatment = Bincode.readBool(bytes, cursor)
        cursor = d_childDirectedTreatment.consumed
        val childDirectedTreatment = d_childDirectedTreatment.value
        return Bincode.Decoded(AdMobConfig(appId = appId, testDeviceIds = testDeviceIds, childDirectedTreatment = childDirectedTreatment), cursor)
    }

    override fun writeAdMobConfig(out: ByteArrayOutputStream, value: AdMobConfig) {
        Bincode.writeString(out, value.appId)
        Bincode.writeVec(out, value.testDeviceIds) { s, v -> Bincode.writeString(s, v) }
        Bincode.writeBool(out, value.childDirectedTreatment)
    }

    override fun readBannerRect(bytes: ByteArray, offset: Int): Bincode.Decoded<BannerRect> {
        var cursor = offset
        val d_x = Bincode.readVarintU64(bytes, cursor).let { Bincode.Decoded(it.value.toUInt(), it.consumed) }
        cursor = d_x.consumed
        val x = d_x.value
        val d_y = Bincode.readVarintU64(bytes, cursor).let { Bincode.Decoded(it.value.toUInt(), it.consumed) }
        cursor = d_y.consumed
        val y = d_y.value
        val d_width = Bincode.readVarintU64(bytes, cursor).let { Bincode.Decoded(it.value.toUInt(), it.consumed) }
        cursor = d_width.consumed
        val width = d_width.value
        val d_height = Bincode.readVarintU64(bytes, cursor).let { Bincode.Decoded(it.value.toUInt(), it.consumed) }
        cursor = d_height.consumed
        val height = d_height.value
        return Bincode.Decoded(BannerRect(x = x, y = y, width = width, height = height), cursor)
    }

    override fun writeBannerRect(out: ByteArrayOutputStream, value: BannerRect) {
        Bincode.writeVarintU64(out, value.x.toLong())
        Bincode.writeVarintU64(out, value.y.toLong())
        Bincode.writeVarintU64(out, value.width.toLong())
        Bincode.writeVarintU64(out, value.height.toLong())
    }

    override fun readBannerRequest(bytes: ByteArray, offset: Int): Bincode.Decoded<BannerRequest> {
        var cursor = offset
        val d_adUnitId = Bincode.readString(bytes, cursor)
        cursor = d_adUnitId.consumed
        val adUnitId = d_adUnitId.value
        val d_rect = readBannerRect(bytes, cursor)
        cursor = d_rect.consumed
        val rect = d_rect.value
        return Bincode.Decoded(BannerRequest(adUnitId = adUnitId, rect = rect), cursor)
    }

    override fun writeBannerRequest(out: ByteArrayOutputStream, value: BannerRequest) {
        Bincode.writeString(out, value.adUnitId)
        writeBannerRect(out, value.rect)
    }

    override fun readInterstitialOutcome(bytes: ByteArray, offset: Int): Bincode.Decoded<InterstitialOutcome> {
        val d = Bincode.readVarintU64(bytes, offset)
        val variant = InterstitialOutcome.entries.getOrNull(d.value.toInt())
            ?: error("InterstitialOutcome: unknown discriminant ${d.value}")
        return Bincode.Decoded(variant, d.consumed)
    }

    override fun writeInterstitialOutcome(out: ByteArrayOutputStream, value: InterstitialOutcome) {
        Bincode.writeEnumDiscriminant(out, value.ordinal)
    }

    override fun readRewardedOutcome(bytes: ByteArray, offset: Int): Bincode.Decoded<RewardedOutcome> {
        var cursor = offset
        val d_granted = Bincode.readBool(bytes, cursor)
        cursor = d_granted.consumed
        val granted = d_granted.value
        val d_rewardType = Bincode.readString(bytes, cursor)
        cursor = d_rewardType.consumed
        val rewardType = d_rewardType.value
        val d_rewardAmount = Bincode.readVarintU64(bytes, cursor).let { Bincode.Decoded(it.value.toUInt(), it.consumed) }
        cursor = d_rewardAmount.consumed
        val rewardAmount = d_rewardAmount.value
        return Bincode.Decoded(RewardedOutcome(granted = granted, rewardType = rewardType, rewardAmount = rewardAmount), cursor)
    }

    override fun writeRewardedOutcome(out: ByteArrayOutputStream, value: RewardedOutcome) {
        Bincode.writeBool(out, value.granted)
        Bincode.writeString(out, value.rewardType)
        Bincode.writeVarintU64(out, value.rewardAmount.toLong())
    }

    override fun readAdError(bytes: ByteArray, offset: Int): Bincode.Decoded<AdError> {
        var cursor = offset
        val disc = Bincode.readVarintU64(bytes, cursor)
        cursor = disc.consumed
        return when (disc.value.toInt()) {
            0 -> Bincode.Decoded(AdError.NotInitialized, cursor)
            1 -> Bincode.Decoded(AdError.NoFill, cursor)
            2 -> {
                val d_inner = Bincode.readString(bytes, cursor)
                cursor = d_inner.consumed
                val inner = d_inner.value
                Bincode.Decoded(AdError.Network(inner) as AdError, cursor)
            }
            3 -> {
                val d_inner = Bincode.readString(bytes, cursor)
                cursor = d_inner.consumed
                val inner = d_inner.value
                Bincode.Decoded(AdError.InvalidRequest(inner) as AdError, cursor)
            }
            4 -> Bincode.Decoded(AdError.UnknownAd, cursor)
            5 -> {
                val d_inner = Bincode.readString(bytes, cursor)
                cursor = d_inner.consumed
                val inner = d_inner.value
                Bincode.Decoded(AdError.Internal(inner) as AdError, cursor)
            }
            else -> error("AdError: unknown discriminant ${disc.value}")
        }
    }

    override fun writeAdError(out: ByteArrayOutputStream, value: AdError) {
        when (value) {
            AdError.NotInitialized -> Bincode.writeEnumDiscriminant(out, 0)
            AdError.NoFill -> Bincode.writeEnumDiscriminant(out, 1)
            is AdError.Network -> {
                Bincode.writeEnumDiscriminant(out, 2)
                Bincode.writeString(out, value.value)
            }
            is AdError.InvalidRequest -> {
                Bincode.writeEnumDiscriminant(out, 3)
                Bincode.writeString(out, value.value)
            }
            AdError.UnknownAd -> Bincode.writeEnumDiscriminant(out, 4)
            is AdError.Internal -> {
                Bincode.writeEnumDiscriminant(out, 5)
                Bincode.writeString(out, value.value)
            }
        }
    }

    override fun readNativeHandleId(bytes: ByteArray, offset: Int): Bincode.Decoded<NativeHandleId> {
        return Bincode.readVarintU64(bytes, offset)
    }

    override fun writeNativeHandleId(out: ByteArrayOutputStream, value: NativeHandleId) {
        Bincode.writeVarintU64(out, value)
    }
}
