package dev.istmo.runtime

// GENERATED by istmo-build - DO NOT EDIT.
// plugin id: istmo.admob

data class AdMobConfig(
    val appId: String,
    val testDeviceIds: List<String>,
    val childDirectedTreatment: Boolean
)

data class BannerRect(
    val x: UInt,
    val y: UInt,
    val width: UInt,
    val height: UInt
)

data class BannerRequest(
    val adUnitId: String,
    val rect: BannerRect
)

enum class InterstitialOutcome {
    Dismissed,
    FailedToShow
}

data class RewardedOutcome(
    val granted: Boolean,
    val rewardType: String,
    val rewardAmount: UInt
)

sealed class AdError {
    object NotInitialized : AdError()
    object NoFill : AdError()
    data class Network(val value: String) : AdError()
    data class InvalidRequest(val value: String) : AdError()
    object UnknownAd : AdError()
    data class Internal(val value: String) : AdError()
}
