package dev.istmo.runtime

// GENERATED by istmo-build - DO NOT EDIT.
// plugin id: istmo.notifications
import java.io.ByteArrayOutputStream

class NotificationsCodecsImpl : NotificationsCodecs {

    override fun readNotificationImportance(bytes: ByteArray, offset: Int): Bincode.Decoded<NotificationImportance> {
        val d = Bincode.readVarintU64(bytes, offset)
        val variant = NotificationImportance.entries.getOrNull(d.value.toInt())
            ?: error("NotificationImportance: unknown discriminant ${d.value}")
        return Bincode.Decoded(variant, d.consumed)
    }

    override fun writeNotificationImportance(out: ByteArrayOutputStream, value: NotificationImportance) {
        Bincode.writeEnumDiscriminant(out, value.ordinal)
    }

    override fun readNotificationRequest(bytes: ByteArray, offset: Int): Bincode.Decoded<NotificationRequest> {
        var cursor = offset
        val d_title = Bincode.readString(bytes, cursor)
        cursor = d_title.consumed
        val title = d_title.value
        val d_body = Bincode.readString(bytes, cursor)
        cursor = d_body.consumed
        val body = d_body.value
        val d_channelId = Bincode.readString(bytes, cursor)
        cursor = d_channelId.consumed
        val channelId = d_channelId.value
        val d_importance = readNotificationImportance(bytes, cursor)
        cursor = d_importance.consumed
        val importance = d_importance.value
        val d_delaySeconds = Bincode.readOption(bytes, cursor) { p, o -> Bincode.readVarintU64(p, o).let { Bincode.Decoded(it.value.toUInt(), it.consumed) } }
        cursor = d_delaySeconds.consumed
        val delaySeconds = d_delaySeconds.value
        val d_tag = Bincode.readOption(bytes, cursor) { p, o -> Bincode.readString(p, o) }
        cursor = d_tag.consumed
        val tag = d_tag.value
        return Bincode.Decoded(NotificationRequest(title = title, body = body, channelId = channelId, importance = importance, delaySeconds = delaySeconds, tag = tag), cursor)
    }

    override fun writeNotificationRequest(out: ByteArrayOutputStream, value: NotificationRequest) {
        Bincode.writeString(out, value.title)
        Bincode.writeString(out, value.body)
        Bincode.writeString(out, value.channelId)
        writeNotificationImportance(out, value.importance)
        Bincode.writeOption(out, value.delaySeconds) { s, v -> Bincode.writeVarintU64(s, v.toLong()) }
        Bincode.writeOption(out, value.tag) { s, v -> Bincode.writeString(s, v) }
    }

    override fun readNotificationHandle(bytes: ByteArray, offset: Int): Bincode.Decoded<NotificationHandle> {
        var cursor = offset
        val d_id = Bincode.readVarintU64(bytes, cursor).let { Bincode.Decoded(it.value.toUInt(), it.consumed) }
        cursor = d_id.consumed
        val id = d_id.value
        return Bincode.Decoded(NotificationHandle(id = id), cursor)
    }

    override fun writeNotificationHandle(out: ByteArrayOutputStream, value: NotificationHandle) {
        Bincode.writeVarintU64(out, value.id.toLong())
    }

    override fun readNotificationError(bytes: ByteArray, offset: Int): Bincode.Decoded<NotificationError> {
        var cursor = offset
        val disc = Bincode.readVarintU64(bytes, cursor)
        cursor = disc.consumed
        return when (disc.value.toInt()) {
            0 -> Bincode.Decoded(NotificationError.PermissionDenied, cursor)
            1 -> {
                val d_inner = Bincode.readString(bytes, cursor)
                cursor = d_inner.consumed
                val inner = d_inner.value
                Bincode.Decoded(NotificationError.InvalidChannel(inner) as NotificationError, cursor)
            }
            2 -> {
                val d_inner = Bincode.readString(bytes, cursor)
                cursor = d_inner.consumed
                val inner = d_inner.value
                Bincode.Decoded(NotificationError.Scheduler(inner) as NotificationError, cursor)
            }
            else -> error("NotificationError: unknown discriminant ${disc.value}")
        }
    }

    override fun writeNotificationError(out: ByteArrayOutputStream, value: NotificationError) {
        when (value) {
            NotificationError.PermissionDenied -> Bincode.writeEnumDiscriminant(out, 0)
            is NotificationError.InvalidChannel -> {
                Bincode.writeEnumDiscriminant(out, 1)
                Bincode.writeString(out, value.value)
            }
            is NotificationError.Scheduler -> {
                Bincode.writeEnumDiscriminant(out, 2)
                Bincode.writeString(out, value.value)
            }
        }
    }
}
