package dev.istmo.runtime

// GENERATED by istmo-build - DO NOT EDIT.
// plugin id: istmo.notifications

enum class NotificationImportance {
    Min,
    Low,
    Default,
    High
}

data class NotificationRequest(
    val title: String,
    val body: String,
    val channelId: String,
    val importance: NotificationImportance,
    val delaySeconds: UInt?,
    val tag: String?
)

data class NotificationHandle(
    val id: UInt
)

sealed class NotificationError {
    object PermissionDenied : NotificationError()
    data class InvalidChannel(val value: String) : NotificationError()
    data class Scheduler(val value: String) : NotificationError()
}
