package dev.istmo.runtime

// GENERATED by istmo-build - DO NOT EDIT.
// plugin id: istmo.google_sign_in
import java.io.ByteArrayOutputStream

class SignInCodecsImpl : SignInCodecs {

    override fun readSignInMode(bytes: ByteArray, offset: Int): Bincode.Decoded<SignInMode> {
        val d = Bincode.readVarintU64(bytes, offset)
        val variant = SignInMode.entries.getOrNull(d.value.toInt())
            ?: error("SignInMode: unknown discriminant ${d.value}")
        return Bincode.Decoded(variant, d.consumed)
    }

    override fun writeSignInMode(out: ByteArrayOutputStream, value: SignInMode) {
        Bincode.writeEnumDiscriminant(out, value.ordinal)
    }

    override fun readSignInConfig(bytes: ByteArray, offset: Int): Bincode.Decoded<SignInConfig> {
        var cursor = offset
        val d_serverClientId = Bincode.readString(bytes, cursor)
        cursor = d_serverClientId.consumed
        val serverClientId = d_serverClientId.value
        val d_scopes = Bincode.readVec(bytes, cursor) { p, o -> Bincode.readString(p, o) }
        cursor = d_scopes.consumed
        val scopes = d_scopes.value
        val d_hostedDomain = Bincode.readOption(bytes, cursor) { p, o -> Bincode.readString(p, o) }
        cursor = d_hostedDomain.consumed
        val hostedDomain = d_hostedDomain.value
        val d_nonce = Bincode.readOption(bytes, cursor) { p, o -> Bincode.readString(p, o) }
        cursor = d_nonce.consumed
        val nonce = d_nonce.value
        val d_autoSelect = Bincode.readBool(bytes, cursor)
        cursor = d_autoSelect.consumed
        val autoSelect = d_autoSelect.value
        return Bincode.Decoded(SignInConfig(serverClientId = serverClientId, scopes = scopes, hostedDomain = hostedDomain, nonce = nonce, autoSelect = autoSelect), cursor)
    }

    override fun writeSignInConfig(out: ByteArrayOutputStream, value: SignInConfig) {
        Bincode.writeString(out, value.serverClientId)
        Bincode.writeVec(out, value.scopes) { s, v -> Bincode.writeString(s, v) }
        Bincode.writeOption(out, value.hostedDomain) { s, v -> Bincode.writeString(s, v) }
        Bincode.writeOption(out, value.nonce) { s, v -> Bincode.writeString(s, v) }
        Bincode.writeBool(out, value.autoSelect)
    }

    override fun readSignInAccount(bytes: ByteArray, offset: Int): Bincode.Decoded<SignInAccount> {
        var cursor = offset
        val d_id = Bincode.readString(bytes, cursor)
        cursor = d_id.consumed
        val id = d_id.value
        val d_email = Bincode.readOption(bytes, cursor) { p, o -> Bincode.readString(p, o) }
        cursor = d_email.consumed
        val email = d_email.value
        val d_displayName = Bincode.readOption(bytes, cursor) { p, o -> Bincode.readString(p, o) }
        cursor = d_displayName.consumed
        val displayName = d_displayName.value
        val d_photoUrl = Bincode.readOption(bytes, cursor) { p, o -> Bincode.readString(p, o) }
        cursor = d_photoUrl.consumed
        val photoUrl = d_photoUrl.value
        val d_idToken = Bincode.readString(bytes, cursor)
        cursor = d_idToken.consumed
        val idToken = d_idToken.value
        val d_grantedScopes = Bincode.readVec(bytes, cursor) { p, o -> Bincode.readString(p, o) }
        cursor = d_grantedScopes.consumed
        val grantedScopes = d_grantedScopes.value
        val d_credential = readNativeHandleId(bytes, cursor)
        cursor = d_credential.consumed
        val credential = d_credential.value
        return Bincode.Decoded(SignInAccount(id = id, email = email, displayName = displayName, photoUrl = photoUrl, idToken = idToken, grantedScopes = grantedScopes, credential = credential), cursor)
    }

    override fun writeSignInAccount(out: ByteArrayOutputStream, value: SignInAccount) {
        Bincode.writeString(out, value.id)
        Bincode.writeOption(out, value.email) { s, v -> Bincode.writeString(s, v) }
        Bincode.writeOption(out, value.displayName) { s, v -> Bincode.writeString(s, v) }
        Bincode.writeOption(out, value.photoUrl) { s, v -> Bincode.writeString(s, v) }
        Bincode.writeString(out, value.idToken)
        Bincode.writeVec(out, value.grantedScopes) { s, v -> Bincode.writeString(s, v) }
        writeNativeHandleId(out, value.credential)
    }

    override fun readSignInError(bytes: ByteArray, offset: Int): Bincode.Decoded<SignInError> {
        var cursor = offset
        val disc = Bincode.readVarintU64(bytes, cursor)
        cursor = disc.consumed
        return when (disc.value.toInt()) {
            0 -> Bincode.Decoded(SignInError.UserCancelled, cursor)
            1 -> Bincode.Decoded(SignInError.NoCredentialAvailable, cursor)
            2 -> Bincode.Decoded(SignInError.Reauthenticate, cursor)
            3 -> {
                val d_inner = Bincode.readString(bytes, cursor)
                cursor = d_inner.consumed
                val inner = d_inner.value
                Bincode.Decoded(SignInError.InvalidConfiguration(inner) as SignInError, cursor)
            }
            4 -> {
                val d_inner = Bincode.readString(bytes, cursor)
                cursor = d_inner.consumed
                val inner = d_inner.value
                Bincode.Decoded(SignInError.Network(inner) as SignInError, cursor)
            }
            5 -> {
                val d_inner = Bincode.readString(bytes, cursor)
                cursor = d_inner.consumed
                val inner = d_inner.value
                Bincode.Decoded(SignInError.Backend(inner) as SignInError, cursor)
            }
            else -> error("SignInError: unknown discriminant ${disc.value}")
        }
    }

    override fun writeSignInError(out: ByteArrayOutputStream, value: SignInError) {
        when (value) {
            SignInError.UserCancelled -> Bincode.writeEnumDiscriminant(out, 0)
            SignInError.NoCredentialAvailable -> Bincode.writeEnumDiscriminant(out, 1)
            SignInError.Reauthenticate -> Bincode.writeEnumDiscriminant(out, 2)
            is SignInError.InvalidConfiguration -> {
                Bincode.writeEnumDiscriminant(out, 3)
                Bincode.writeString(out, value.value)
            }
            is SignInError.Network -> {
                Bincode.writeEnumDiscriminant(out, 4)
                Bincode.writeString(out, value.value)
            }
            is SignInError.Backend -> {
                Bincode.writeEnumDiscriminant(out, 5)
                Bincode.writeString(out, value.value)
            }
        }
    }

    override fun readNativeHandleId(bytes: ByteArray, offset: Int): Bincode.Decoded<NativeHandleId> {
        return Bincode.readVarintU64(bytes, offset)
    }

    override fun writeNativeHandleId(out: ByteArrayOutputStream, value: NativeHandleId) {
        Bincode.writeVarintU64(out, value)
    }
}
