//! `istmo::runtime!` function-like macro.
//!
//! Emits the single wiring point every process needs:
//!
//! ```ignore
//! istmo::runtime!(
//!     plugins: [Permissions, ActivityResults],
//!     hosts:   [Echo => EchoImpl],
//! );
//! ```
//!
//! Expansion (schematically):
//!
//! ```ignore
//! #[cfg(target_os = "android")]
//! pub use ::istmo_android::entrypoint::*;
//!
//! #[unsafe(no_mangle)]
//! pub fn __istmo_configure_runtime(init: ::istmo::RuntimeInit) -> ::istmo::RuntimeInit {
//!     init
//!         .expects::<::istmo::plugins::PermissionsClient>()
//!         .expects::<::istmo::plugins::ActivityResultsClient>()
//!         .host(EchoHost::new(EchoImpl))
//!         .finish()
//! }
//! ```
//!
//! - `plugins: [TClient, ...]` — each entry is a plugin CLIENT type as
//!   generated by `#[istmo::plugin]`; the macro passes it through to
//!   `.expects::<TClient>()`.
//! - `hosts: [T => Expr, ...]` — each `T` is a plugin trait name; the macro
//!   takes `<T>Host` and calls `.host(THost::new(Expr))`.
//! - `remote: [T, ...]` — each `T` is a plugin trait name; the macro takes
//!   `<T>Client` and calls `.remotes::<TClient>()`. Declares that the
//!   plugin lives on the far side of a `:remote` bridge. Same trait ids
//!   must be listed on both peers.
//!
//! All sections are optional and can appear in any order. On android the
//! `pub use` block pins the five JNI trampolines so `--gc-sections` does not
//! strip them out of the `.so`; on Apple mobile / wearable / TV / vision
//! targets the same pattern re-exports the `istmo-ios` `@_cdecl` symbols.
//! On other targets the macro emits only the configuration function so
//! `Runtime::mock()` / `cargo run` share the same wiring path.

use proc_macro2::TokenStream;
use quote::quote;
use syn::punctuated::Punctuated;
use syn::{Expr, Ident, Token, bracketed, parse::Parse, parse::ParseStream, parse2};

#[allow(unreachable_pub)]
pub fn expand(input: TokenStream) -> syn::Result<TokenStream> {
    let RuntimeInput {
        plugins,
        hosts,
        services,
        workers,
        remote,
    } = parse2::<RuntimeInput>(input)?;

    // `plugins:` entries are the plugin CLIENT types (e.g. `PermissionsClient`
    // as generated by `#[istmo::plugin]`). Users import them from the plugin
    // crate; the macro just passes them through to `.expects::<T>()`.
    let expects_calls = plugins.iter().map(|client_ident| {
        quote! { .expects::<#client_ident>() }
    });

    // `remote:` entries are plugin TRAIT names (e.g. `ExpensiveCompute`);
    // the macro reaches through to the generated Client type to read
    // `<TraitClient as Plugin>::PLUGIN_ID` and pass it to `.remotes::<T>()`.
    // Trait-name shape keeps `remote:` symmetric with `hosts:`; users still
    // have to import `<Trait>Client` on the remote-proc side to make the
    // path resolve.
    let remote_calls = remote.iter().map(|trait_ident| {
        let client_ident = quote::format_ident!("{}Client", trait_ident);
        quote! { .remotes::<#client_ident>() }
    });

    // `hosts:` entries are `Trait => Expr` where `Trait` is the plugin trait
    // name; the macro rewrites to `<Trait>Host::new(Expr)`.
    let host_calls = hosts.iter().map(
        |HostEntry {
             trait_ident,
             impl_expr,
         }| {
            let host_ident = quote::format_ident!("{}Host", trait_ident);
            quote! { .host(#host_ident::new(#impl_expr)) }
        },
    );

    // `services:` entries are `Trait => Expr` where `Trait` was annotated
    // with `#[istmo::service]`; the macro rewrites to
    // `<Trait>ServiceAdapter::new(Expr)`.
    let service_calls = services.iter().map(
        |HostEntry {
             trait_ident,
             impl_expr,
         }| {
            let adapter_ident = quote::format_ident!("{}Adapter", trait_ident);
            quote! { .host(#adapter_ident::new(#impl_expr)) }
        },
    );

    // `workers:` entries are `Trait => Expr` where `Trait` was annotated
    // with `#[istmo::worker]`; the macro rewrites to
    // `<Trait>WorkerAdapter::new(Expr)`.
    let worker_calls = workers.iter().map(
        |HostEntry {
             trait_ident,
             impl_expr,
         }| {
            let adapter_ident = quote::format_ident!("{}WorkerAdapter", trait_ident);
            quote! { .host(#adapter_ident::new(#impl_expr)) }
        },
    );

    Ok(quote! {
        #[cfg(target_os = "android")]
        #[allow(unused_imports)]
        pub use ::istmo::android::entrypoint::*;

        #[cfg(any(
            target_os = "ios",
            target_os = "tvos",
            target_os = "watchos",
            target_os = "visionos",
        ))]
        #[allow(unused_imports)]
        pub use ::istmo::ios::entrypoint::*;

        #[doc(hidden)]
        #[unsafe(no_mangle)]
        pub fn __istmo_configure_runtime(
            init: ::istmo::RuntimeInit,
        ) -> ::istmo::RuntimeInit {
            init
                #(#expects_calls)*
                #(#remote_calls)*
                #(#host_calls)*
                #(#service_calls)*
                #(#worker_calls)*
                .finish()
        }
    })
}

struct RuntimeInput {
    plugins: Vec<Ident>,
    hosts: Vec<HostEntry>,
    services: Vec<HostEntry>,
    workers: Vec<HostEntry>,
    remote: Vec<Ident>,
}

struct HostEntry {
    trait_ident: Ident,
    impl_expr: Expr,
}

impl Parse for RuntimeInput {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        let mut plugins = Vec::new();
        let mut hosts = Vec::new();
        let mut services = Vec::new();
        let mut workers = Vec::new();
        let mut remote = Vec::new();

        while !input.is_empty() {
            let key: Ident = input.parse()?;
            input.parse::<Token![:]>()?;
            match key.to_string().as_str() {
                "plugins" => {
                    let content;
                    bracketed!(content in input);
                    let list: Punctuated<Ident, Token![,]> =
                        Punctuated::parse_terminated(&content)?;
                    plugins.extend(list);
                }
                "hosts" => {
                    let content;
                    bracketed!(content in input);
                    let list: Punctuated<HostEntry, Token![,]> =
                        Punctuated::parse_terminated(&content)?;
                    hosts.extend(list);
                }
                "services" => {
                    let content;
                    bracketed!(content in input);
                    let list: Punctuated<HostEntry, Token![,]> =
                        Punctuated::parse_terminated(&content)?;
                    services.extend(list);
                }
                "workers" => {
                    let content;
                    bracketed!(content in input);
                    let list: Punctuated<HostEntry, Token![,]> =
                        Punctuated::parse_terminated(&content)?;
                    workers.extend(list);
                }
                "remote" => {
                    let content;
                    bracketed!(content in input);
                    let list: Punctuated<Ident, Token![,]> =
                        Punctuated::parse_terminated(&content)?;
                    remote.extend(list);
                }
                other => {
                    return Err(syn::Error::new(
                        key.span(),
                        format!(
                            "unknown section `{other}`; expected `plugins`, `remote`, `hosts`, `services` or `workers`"
                        ),
                    ));
                }
            }
            // trailing comma between sections is optional
            let _: Option<Token![,]> = input.parse().ok();
        }

        Ok(Self {
            plugins,
            hosts,
            services,
            workers,
            remote,
        })
    }
}

impl Parse for HostEntry {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        let trait_ident: Ident = input.parse()?;
        input.parse::<Token![=>]>()?;
        let impl_expr: Expr = input.parse()?;
        Ok(Self {
            trait_ident,
            impl_expr,
        })
    }
}
