// GENERATED by istmo-build - DO NOT EDIT MANUALLY.
//
// Regenerate by running the codegen test suite and copying the golden
// output verbatim:
//
//   ISTMO_BUILD_UPDATE_GOLDEN=1 cargo test -p istmo-build --test codegen
//   cp crates/build/tests/golden/notifications_host.swift.expected \
//      examples/rust-mobile-demo/ios/RustMobileDemo/Plugins/Notifications/NotificationsDispatcher.swift
//
// plugin id: istmo.notifications

import Foundation
import IstmoRuntime

/// Platform-facing surface for the `Notifications` plugin. Hand-write an
/// impl with the SDK-specific logic; the dispatcher below handles
/// wire encode/decode.
public protocol NotificationsBackend: AnyObject {
    func is_authorized() async throws -> Bool
    func request_authorization() async throws -> Bool
    /// Throw `NotificationError` to surface a typed domain error.
    func schedule(request: NotificationRequest) async throws -> NotificationHandle
    /// Throw `NotificationError` to surface a typed domain error.
    func cancel(id: UInt32) async throws -> Void
}

/// Reader / writer per `Named` type referenced by the `Notifications` contract.
/// User provides one impl; each entry typically delegates to a
/// helper on the type itself.
public protocol NotificationsCodecs {
    func readNotificationError(_ c: inout Bincode.Cursor) throws -> NotificationError
    func writeNotificationError(_ out: inout Data, _ value: NotificationError)
    func readNotificationHandle(_ c: inout Bincode.Cursor) throws -> NotificationHandle
    func writeNotificationHandle(_ out: inout Data, _ value: NotificationHandle)
    func readNotificationRequest(_ c: inout Bincode.Cursor) throws -> NotificationRequest
    func writeNotificationRequest(_ out: inout Data, _ value: NotificationRequest)
}

/// Decodes wire calls, invokes `NotificationsBackend`, encodes the response.
/// Register with `IstmoRuntime.shared.registerHandler(PLUGIN_ID, dispatcher)`.
public final class NotificationsDispatcher: PluginHandler {
    public static let PLUGIN_ID: String = "istmo.notifications"

    private let backend: NotificationsBackend
    private let codecs: NotificationsCodecs

    public init(backend: NotificationsBackend, codecs: NotificationsCodecs) {
        self.backend = backend
        self.codecs = codecs
    }

    public func handleCall(instanceId: UInt64, method: String, payload: Data) async throws -> Data {
        switch method {
        case "is_authorized":
            let result = try await backend.is_authorized()
            var out = Data()
            Bincode.writeBool(&out, result)
            return out
        case "request_authorization":
            let result = try await backend.request_authorization()
            var out = Data()
            Bincode.writeBool(&out, result)
            return out
        case "schedule":
            do {
                var c = Bincode.Cursor(payload)
                let request = try codecs.readNotificationRequest(&c)
                let result = try await backend.schedule(request: request)
                var out = Data()
                codecs.writeNotificationHandle(&out, result)
                return out
            } catch let err as NotificationError {
                var errOut = Data()
                codecs.writeNotificationError(&errOut, err)
                throw PluginException(payload: errOut)
            }
        case "cancel":
            do {
                var c = Bincode.Cursor(payload)
                let id = try Bincode.readVarintU32(&c)
                try await backend.cancel(id: id)
                return Data()
            } catch let err as NotificationError {
                var errOut = Data()
                codecs.writeNotificationError(&errOut, err)
                throw PluginException(payload: errOut)
            }
        default:
            throw PluginRuntimeError.unknownMethod(plugin: "Notifications", method: method)
        }
    }
}
