// GENERATED by istmo-build - DO NOT EDIT MANUALLY.
//
// Regenerate:
//
//   ISTMO_BUILD_UPDATE_GOLDEN=1 cargo test -p istmo-build --test codegen
//   cp crates/build/tests/golden/admob_host.swift.expected \
//      examples/rust-mobile-demo/ios/RustMobileDemo/Plugins/AdMob/AdMobDispatcher.swift
//
// The one hand-written addition is the `HandleReleaser` conformance on
// `AdMobDispatcher` — it forwards `releaseNativeHandle` to every live
// backend so ad handles Rust drops without calling `show_*` / `hide_*`
// still tear down the underlying SDK object. Add-on codegen is a
// follow-up: emit `HandleReleaser` when the contract references
// `NativeHandleId`.
//
// plugin id: istmo.admob

import Foundation
import IstmoRuntime

/// Platform-facing surface for the `AdMob` plugin. Hand-write an
/// impl with the SDK-specific logic; the dispatcher below handles
/// wire encode/decode.
public protocol AdMobBackend: AnyObject {
    /// Throw `AdError` to surface a typed domain error.
    func load_interstitial(ad_unit_id: String) async throws -> NativeHandleId
    /// Throw `AdError` to surface a typed domain error.
    func show_interstitial(ad: NativeHandleId) async throws -> InterstitialOutcome
    /// Throw `AdError` to surface a typed domain error.
    func load_rewarded(ad_unit_id: String) async throws -> NativeHandleId
    /// Throw `AdError` to surface a typed domain error.
    func show_rewarded(ad: NativeHandleId) async throws -> RewardedOutcome
    /// Throw `AdError` to surface a typed domain error.
    func show_banner(request: BannerRequest) async throws -> NativeHandleId
    /// Throw `AdError` to surface a typed domain error.
    func update_banner(banner: NativeHandleId, rect: BannerRect) async throws -> Void
    /// Throw `AdError` to surface a typed domain error.
    func hide_banner(banner: NativeHandleId) async throws -> Void
}

/// Reader / writer per `Named` type referenced by the `AdMob` contract.
public protocol AdMobCodecs {
    func readAdError(_ c: inout Bincode.Cursor) throws -> AdError
    func writeAdError(_ out: inout Data, _ value: AdError)
    func readAdMobConfig(_ c: inout Bincode.Cursor) throws -> AdMobConfig
    func writeAdMobConfig(_ out: inout Data, _ value: AdMobConfig)
    func readBannerRect(_ c: inout Bincode.Cursor) throws -> BannerRect
    func writeBannerRect(_ out: inout Data, _ value: BannerRect)
    func readBannerRequest(_ c: inout Bincode.Cursor) throws -> BannerRequest
    func writeBannerRequest(_ out: inout Data, _ value: BannerRequest)
    func readInterstitialOutcome(_ c: inout Bincode.Cursor) throws -> InterstitialOutcome
    func writeInterstitialOutcome(_ out: inout Data, _ value: InterstitialOutcome)
    func readNativeHandleId(_ c: inout Bincode.Cursor) throws -> NativeHandleId
    func writeNativeHandleId(_ out: inout Data, _ value: NativeHandleId)
    func readRewardedOutcome(_ c: inout Bincode.Cursor) throws -> RewardedOutcome
    func writeRewardedOutcome(_ out: inout Data, _ value: RewardedOutcome)
}

public protocol AdMobFactory {
    func create(config: AdMobConfig) async throws -> AdMobBackend
}

public final class AdMobDispatcher: PluginHandler, HandleReleaser {
    public static let PLUGIN_ID: String = "istmo.admob"

    private let factory: AdMobFactory
    private let codecs: AdMobCodecs
    private var instances: [UInt64: AdMobBackend] = [:]
    private var nextInstanceId: UInt64 = 1
    private let lock = NSLock()

    public init(factory: AdMobFactory, codecs: AdMobCodecs) {
        self.factory = factory
        self.codecs = codecs
    }

    public func releaseNativeHandle(_ handleId: UInt64) {
        // Every AdMob handle id ultimately points at one specific
        // backend's SDK object. Since only one AdMob instance is alive at
        // a time in the demo, the linear scan is trivially cheap.
        let snapshot = withLock { Array(instances.values) }
        for backend in snapshot {
            if let releaser = backend as? HandleReleaser {
                releaser.releaseNativeHandle(handleId)
            }
        }
    }

    public func handleCreateInstance(payload: Data) async throws -> Data {
        var c = Bincode.Cursor(payload)
        let config = try codecs.readAdMobConfig(&c)
        let backend = try await factory.create(config: config)
        let id: UInt64 = withLock {
            let next = nextInstanceId
            nextInstanceId += 1
            instances[next] = backend
            return next
        }
        var out = Data()
        Bincode.writeVarintU64(&out, id)
        return out
    }

    public func handleCall(instanceId: UInt64, method: String, payload: Data) async throws -> Data {
        let backendOpt = withLock { instances[instanceId] }
        guard let backend = backendOpt else { throw PluginRuntimeError.unknownInstance(instanceId) }
        switch method {
        case "load_interstitial":
            do {
                var c = Bincode.Cursor(payload)
                let ad_unit_id = try Bincode.readString(&c)
                let result = try await backend.load_interstitial(ad_unit_id: ad_unit_id)
                var out = Data()
                codecs.writeNativeHandleId(&out, result)
                return out
            } catch let err as AdError {
                var errOut = Data()
                codecs.writeAdError(&errOut, err)
                throw PluginException(payload: errOut)
            }
        case "show_interstitial":
            do {
                var c = Bincode.Cursor(payload)
                let ad = try codecs.readNativeHandleId(&c)
                let result = try await backend.show_interstitial(ad: ad)
                var out = Data()
                codecs.writeInterstitialOutcome(&out, result)
                return out
            } catch let err as AdError {
                var errOut = Data()
                codecs.writeAdError(&errOut, err)
                throw PluginException(payload: errOut)
            }
        case "load_rewarded":
            do {
                var c = Bincode.Cursor(payload)
                let ad_unit_id = try Bincode.readString(&c)
                let result = try await backend.load_rewarded(ad_unit_id: ad_unit_id)
                var out = Data()
                codecs.writeNativeHandleId(&out, result)
                return out
            } catch let err as AdError {
                var errOut = Data()
                codecs.writeAdError(&errOut, err)
                throw PluginException(payload: errOut)
            }
        case "show_rewarded":
            do {
                var c = Bincode.Cursor(payload)
                let ad = try codecs.readNativeHandleId(&c)
                let result = try await backend.show_rewarded(ad: ad)
                var out = Data()
                codecs.writeRewardedOutcome(&out, result)
                return out
            } catch let err as AdError {
                var errOut = Data()
                codecs.writeAdError(&errOut, err)
                throw PluginException(payload: errOut)
            }
        case "show_banner":
            do {
                var c = Bincode.Cursor(payload)
                let request = try codecs.readBannerRequest(&c)
                let result = try await backend.show_banner(request: request)
                var out = Data()
                codecs.writeNativeHandleId(&out, result)
                return out
            } catch let err as AdError {
                var errOut = Data()
                codecs.writeAdError(&errOut, err)
                throw PluginException(payload: errOut)
            }
        case "update_banner":
            do {
                var c = Bincode.Cursor(payload)
                let banner = try codecs.readNativeHandleId(&c)
                let rect = try codecs.readBannerRect(&c)
                try await backend.update_banner(banner: banner, rect: rect)
                return Data()
            } catch let err as AdError {
                var errOut = Data()
                codecs.writeAdError(&errOut, err)
                throw PluginException(payload: errOut)
            }
        case "hide_banner":
            do {
                var c = Bincode.Cursor(payload)
                let banner = try codecs.readNativeHandleId(&c)
                try await backend.hide_banner(banner: banner)
                return Data()
            } catch let err as AdError {
                var errOut = Data()
                codecs.writeAdError(&errOut, err)
                throw PluginException(payload: errOut)
            }
        default:
            throw PluginRuntimeError.unknownMethod(plugin: "AdMob", method: method)
        }
    }

    private func withLock<T>(_ body: () -> T) -> T {
        lock.lock()
        defer { lock.unlock() }
        return body()
    }
}
