[package]
name = "istmo-core"
version = "0.1.0"
description = "Transport, protocol, routing and per-process runtime for the istmo framework."
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords = ["mobile", "android", "ios", "ffi", "istmo"]
categories = ["development-tools::ffi", "network-programming", "os"]

[dependencies]
bincode = { workspace = true }
flume = { workspace = true }
oneshot = { workspace = true }
pollster = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
