//! Server-side plugin dispatch surface.
//!
//! `#[istmo::plugin]` generates a `Hosted<T: Trait>` struct implementing
//! [`Dispatch`] for every trait declared as a `hosts:` entry in the process's
//! [`crate::runtime`] configuration. The runtime routes inbound
//! [`crate::protocol::Frame::Call`] frames to the dispatcher by
//! [`Dispatch::plugin_id`].
//!
//! A dispatcher decodes the method arguments, calls the concrete `impl Trait
//! for TImpl` method, and returns an [`Outcome`] — the transport layer wraps
//! it in a [`crate::protocol::Frame::Respond`]. Domain errors declared on the
//! trait (`Result<T, E>`) travel through [`Outcome::DomainError`]; they are
//! opaque bytes at this layer.
//!
//! All decode / encode failures surface as typed [`DispatchError`] variants —
//! never as panics.

use core::fmt;
use std::future::Future;
use std::pin::Pin;

use crate::error::CodecError;
use crate::protocol::InstanceId;

/// Terminal outcome of a single hosted method call.
///
/// The transport turns this into `Frame::Respond { result: Ok / Err }`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Outcome {
    /// The method returned a successful value; the bytes are the encoded `T`.
    Ok(Vec<u8>),
    /// The trait signature was `Result<T, E>` and the method returned `Err`;
    /// the bytes are the encoded `E`.
    DomainError(Vec<u8>),
}

/// Failures the dispatch layer surfaces to the runtime. Never a panic path.
#[derive(Debug)]
pub enum DispatchError {
    /// Decoding a method's argument tuple failed.
    Decode(CodecError),
    /// Encoding the return value or domain error failed.
    Encode(CodecError),
    /// The `method` string on the Call frame is not known to this dispatcher.
    UnknownMethod(String),
    /// The method is declared on the trait but its concrete implementation is
    /// not yet available on this platform (typically stream methods on the
    /// hosted side, which the M-current codegen leaves as a TODO).
    Unimplemented(&'static str),
}

impl fmt::Display for DispatchError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Decode(err) => write!(f, "dispatch decode: {err}"),
            Self::Encode(err) => write!(f, "dispatch encode: {err}"),
            Self::UnknownMethod(name) => write!(f, "unknown method: {name}"),
            Self::Unimplemented(name) => write!(f, "unimplemented method: {name}"),
        }
    }
}

impl std::error::Error for DispatchError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Decode(err) | Self::Encode(err) => Some(err),
            Self::UnknownMethod(_) | Self::Unimplemented(_) => None,
        }
    }
}

/// A future returned by [`Dispatch::dispatch`]. Boxed to let the trait be
/// object-safe — the runtime holds dispatchers behind `Arc<dyn Dispatch>`.
pub type DispatchFuture<'a> =
    Pin<Box<dyn Future<Output = Result<Outcome, DispatchError>> + Send + 'a>>;

/// Marker trait implemented by every generated plugin client and host so that
/// generic runtime helpers can name the wire plugin id without threading a
/// separate `&'static str` argument.
pub trait Plugin {
    /// Wire identifier of the plugin.
    const PLUGIN_ID: &'static str;
}

/// Server-side dispatch surface for a single plugin trait.
///
/// Generated by `#[istmo::plugin]`. The runtime treats every implementer
/// uniformly; each concrete dispatcher owns its `impl Trait for TImpl`
/// instance.
pub trait Dispatch: Send + Sync + 'static {
    /// The wire plugin id this dispatcher handles.
    fn plugin_id(&self) -> &'static str;

    /// Handle a single Call frame. The runtime provides the instance id
    /// (`None` for stateless plugins), the method name and the argument
    /// payload bytes; the dispatcher decodes the arguments, invokes the
    /// concrete impl and returns an [`Outcome`].
    fn dispatch<'a>(
        &'a self,
        instance_id: Option<InstanceId>,
        method: &'a str,
        payload: &'a [u8],
    ) -> DispatchFuture<'a>;
}
